# Import-UsingStatements-IntoProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



Import-Module -Name "../../Modules/String.ManipulationModule/String.ManipulationModule.psm1" -WarningAction SilentlyContinue



$REGEX_AUTOGENERATED_TEXT = "#<([\S\s]*?)>#"
$SEPARATOR                = "### ===================================================================================="
$GITHUB_REPOSITORY        = "https://github.com/ElianFabian/powershell-utils"

$modules = (Get-ChildItem -Path "../../Modules/AutogeneratedModules" -Recurse -File).BaseName

$usingModuleStatements = ""
foreach ($module in $modules)
{
    $usingModuleStatements += "using module $module`n"
}

$autogeneratedText = @(
    "#<### Modules imported with Import-UsingStatements-IntoProfile.ps1",
    "# Date when the modules were added: $(Get-Date)",
    "# Repository of the modules:        $GITHUB_REPOSITORY",
    $SEPARATOR, '',
    $usingModuleStatements,
    "$SEPARATOR>#"
) -join "`n"


$newValue = AddOrUpdate-ValueInString `
    -ValueToAddOrUpdate $autogeneratedText `
    -ValueRegex         $REGEX_AUTOGENERATED_TEXT `
    -ValueKey           $GITHUB_REPOSITORY `
    -SourceString       (Get-Content -Path $PROFILE -Raw) `
    -AddValue {
        param($sourceString, $valueToAdd)

        return $valueToAdd + $sourceString
    }

Set-Content -Path $PROFILE -Value $newValue -NoNewline
