# Import-UsingStatements-IntoProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



$REGEX_AUTOGENERATED_TEXT = "#<([\S\s]*?)>#"
$SEPARATOR                = "### ===================================================================================="
$GITHUB_REPOSITORY        = "https://github.com/ElianFabian/powershell-utils"

$modules = (Get-ChildItem -Path "../../Modules/AutogeneratedModules" -Recurse -File).BaseName

$usingModuleStatements = ""
foreach ($module in $modules)
{
    $usingModuleStatements += "using module $module`n"
}

$autogeneratedText = @(
    "#<### Modules imported with Import-UsingStatements-IntoProfile.ps1",
    "# Date when the modules were added: $(Get-Date)",
    "# Repository of the modules:        $GITHUB_REPOSITORY",
    $SEPARATOR, '',
    $usingModuleStatements,
    "$SEPARATOR>#"
) -join "`n"


$previousContent          = Get-Content -Path $PROFILE -Raw
$autogeneratedTextMatches = ($previousContent | Select-String -Pattern $REGEX_AUTOGENERATED_TEXT -AllMatches).Matches

#region Prepend
if ($null -eq $autogeneratedTextMatches)
{
    $newContent = $autogeneratedText + $previousContent

    Set-Content -Path $PROFILE -Value $newContent
}
#endregion
#region Update
else
{
    foreach ($match in $autogeneratedTextMatches)
    {
        if (-not $match.Value.Contains($GITHUB_REPOSITORY)) { continue }

        $autogeneratedTextUpdated = $previousContent -replace $match.Value, $autogeneratedText

        Set-Content -Path $PROFILE -Value $autogeneratedTextUpdated -NoNewline

        break
    }
}
#endregion
