# Import-UsingStatements-IntoProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



$REGEX_AUTOGENERATED_TEXT = "#<([\S\s]*?)>#"
$SEPARATOR                = "### ===================================================================================="
$GITHUB_REPOSITORY        = "https://github.com/ElianFabian/powershell-utils"

$modules = (Get-ChildItem -Path "../../Modules/AutogeneratedModules").BaseName

$usingModuleStatments = foreach ($module in $modules)
{
    "using module $module`n"
}

$autogeneratedText = @(
    "#<### Modules imported with Import-UsingStatements-IntoProfile.ps1",
    "# Date when modules were added: $(Get-Date)",
    "# Repository of the modules:    $GITHUB_REPOSITORY",
    $SEPARATOR, '',
    $usingModuleStatments,
    "$SEPARATOR>#"
) -join "`n"


$previousContent          = Get-Content -Path $PROFILE -Raw
$autogeneratedTextMatches = (Select-String -InputObject $previousContent -Pattern $REGEX_AUTOGENERATED_TEXT -AllMatches).Matches

if ($null -eq $autogeneratedTextMatches) # If there are no matches then no using statement was added, so we prepend it
{
    $newContent = $autogeneratedText + $previousContent

    Set-Content -Path $PROFILE -Value $newContent
}
else # Else we update all the existing ones
{
    foreach ($match in $autogeneratedTextMatches)
    {
        if ($match.Value.Contains($GITHUB_REPOSITORY))
        {
            $autogeneratedTextUpdated = $previousContent -replace $match.Value, $autogeneratedText

            Set-Content -Path $PROFILE -Value $autogeneratedTextUpdated -NoNewline

            break
        }
    }
}
