# Remove-UsingModuleStatements-IntoProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



$autogeneratedTextRegex = "<#([\S\s]*?)#>"

$githubRepository = "https://github.com/ElianFabian/powershell-utils"

# Converts the $PROFILE file into unix to be able to read it properly (if this is not done, the regex match does not work)
((Get-Content $PROFILE) -join "`n") + "`n" | Set-Content -NoNewline $PROFILE

$previousContent = Get-Content -Path $PROFILE -Raw

$autogeneratedTextMatches = Select-String -InputObject $previousContent -Pattern $autogeneratedTextRegex -AllMatches

foreach ($match in $autogeneratedTextMatches.Matches)
{
    if ($match.Value.Contains($githubRepository))
    {
        $profileContentUpdated = $previousContent -replace $match.Value, ""

        Set-Content -Path $PROFILE -Value $profileContentUpdated -NoNewline
        Start-Process notepad $PROFILE

        break
    }
}
