# Remove-UsingStatements-FromProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



$autogeneratedTextRegex = "#<([\S\s]*?)>#"

$githubRepository = "https://github.com/ElianFabian/powershell-utils"


$previousContent = Get-Content -Path $PROFILE -Raw

$autogeneratedTextMatches = Select-String -InputObject $previousContent -Pattern $autogeneratedTextRegex -AllMatches

foreach ($match in $autogeneratedTextMatches.Matches)
{
    if ($match.Value.Contains($githubRepository))
    {
        $profileContentUpdated = $previousContent -replace $match.Value, ""

        Set-Content -Path $PROFILE -Value $profileContentUpdated -NoNewline

        break
    }
}
