# Remove-UsingStatements-FromProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



$REGEX_AUTOGENERATED_TEXT = "#<([\S\s]*?)>#"
$GITHUB_REPOSITORY        = "https://github.com/ElianFabian/powershell-utils"

$previousContent          = Get-Content -Path $PROFILE -Raw
$autogeneratedTextMatches = (Select-String -InputObject $previousContent -Pattern $REGEX_AUTOGENERATED_TEXT -AllMatches).Matches


foreach ($match in $autogeneratedTextMatches)
{
    if ($match.Value.Contains($GITHUB_REPOSITORY))
    {
        $profileContentUpdated = $previousContent -replace $match.Value, ""

        Set-Content -Path $PROFILE -Value $profileContentUpdated -NoNewline

        break
    }
}
