# AutogeneratedEnumModule.psm1


# This file was generated by Autogenerate-EnumModule.ps1


# This file will be import in C:\Users\Elián\Documents\PowerShell\Microsoft.PowerShell_profile.ps1 with a using statement to use its enums


#region From: String.CaseModule.psm1

enum CaseType
{
	CamelCase      # camelCase
	PascalCase     # PascalCase
	SnakeCase      # snake_case
	UpperSnakeCase # SNAKE_CASE
	KebabCase      # kebab-case
	TrainCase      # Train-Case
}

#endregion


