# Append-UsingModuleStatements-IntoProfile.ps1



# From repository: https://github.com/ElianFabian/powershell-utils



# In this file we have to add the modules that contains classes or enums because they need to be imported with the "using module" statement.


$autogeneratedTextRegex = "\n\n###(.|\n)*=\n"


$modules = @(
    "EnumModule"
)

$usingModuleStatments = ""

foreach ($module in $modules)
{
    $usingModuleStatments += "using module $module`n"
}


$SEPARATOR = "### ===================================================================================="


$autogeneratedText = @"


### Modules added with Append-UsingModuleStatements-IntoProfile.ps1
# Date when modules were added: $(Get-Date)
# Repository of the modules:    https://github.com/ElianFabian/powershell-utils
$SEPARATOR

$usingModuleStatments
$SEPARATOR
"@

# Converts the $PROFILE file into unix to be able to read it properly (if this is not done, the regex match does not work)
((Get-Content $PROFILE) -join "`n") + "`n" | Set-Content -NoNewline $PROFILE

$previousContent = Get-Content -Path $PROFILE -Raw

$newContent = $previousContent -replace $autogeneratedTextRegex, $autogeneratedText

Set-Content -Path $PROFILE -Value $newContent

Start-Process notepad $PROFILE
